# Compose file for development
services:
  postgres:
    image: postgres:17-alpine
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
